# Generated by Django 5.2 on 2025-04-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_id', models.CharField(max_length=20, unique=True)),
                ('username', models.CharField(max_length=100)),
                ('discriminator', models.CharField(max_length=5)),
                ('points', models.IntegerField(default=0)),
                ('is_banned', models.BooleanField(default=False)),
            ],
        ),
    ]
