# Generated by Django 5.2 on 2025-04-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discorduser',
            name='is_banned',
        ),
        migrations.AddField(
            model_name='discorduser',
            name='banned_lvl',
            field=models.IntegerField(default=0),
        ),
    ]
