# Generated by Django 5.2 on 2025-04-17 17:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_discorduser_is_banned_discorduser_banned_lvl'),
    ]

    operations = [
        migrations.AddField(
            model_name='discorduser',
            name='ban_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='banned_lvl',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
